name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5

    - name: Install
      run: |
        pip install mkdocs-material
        pip install mkdocs-mermaid2-plugin

    - name: Deploy
      run: mkdocs gh-deploy --force